// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbUoN9hFGENyAurF4jCvaXFH91Qj7Bj3c',
    appId: '1:391171501698:web:d7b46489e3bf6ae12ece9b',
    messagingSenderId: '391171501698',
    projectId: 'project-pemrograman-mobi-ec01c',
    authDomain: 'project-pemrograman-mobi-ec01c.firebaseapp.com',
    storageBucket: 'project-pemrograman-mobi-ec01c.firebasestorage.app',
    measurementId: 'G-9Q3SPQPWTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdnP6QUV4RpJL-tJM1KAxm_4IDgwvjDEQ',
    appId: '1:391171501698:android:5d1b491eae51e69b2ece9b',
    messagingSenderId: '391171501698',
    projectId: 'project-pemrograman-mobi-ec01c',
    storageBucket: 'project-pemrograman-mobi-ec01c.firebasestorage.app',
  );
}
